#! /bin/bash

clear

./program imagen720p.jpg  miImagen720p-480p.jpg 1

./program imagen720p.jpg  miImagen720p-480p.jpg 2

./program imagen720p.jpg  miImagen720p-480p.jpg 4

./program imagen720p.jpg  miImagen720p-480p.jpg 8

./program imagen720p.jpg  miImagen720p-480p.jpg 16

./program imagen1080p.jpg  miImagen1080p-480p.jpg 1

./program imagen1080p.jpg  miImagen1080p-480p.jpg 2

./program imagen1080p.jpg  miImagen1080p-480p.jpg 4

./program imagen1080p.jpg  miImagen1080p-480p.jpg 8

./program imagen1080p.jpg  miImagen1080p-480p.jpg 16

./program imagen4k.jpg  miImagen4k-480p.jpg 1

./program imagen4k.jpg  miImagen4k-480p.jpg 2

./program imagen4k.jpg  miImagen4k-480p.jpg 4

./program imagen4k.jpg  miImagen4k-480p.jpg 8

./program imagen4k.jpg  miImagen4k-480p.jpg 16